// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wsrpc.proto

package wsrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 1
type Message struct {
	Contents             string   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *Message) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type ClientHello struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHello) Reset()         { *m = ClientHello{} }
func (m *ClientHello) String() string { return proto.CompactTextString(m) }
func (*ClientHello) ProtoMessage()    {}
func (*ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{1}
}

func (m *ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHello.Unmarshal(m, b)
}
func (m *ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHello.Marshal(b, m, deterministic)
}
func (m *ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHello.Merge(m, src)
}
func (m *ClientHello) XXX_Size() int {
	return xxx_messageInfo_ClientHello.Size(m)
}
func (m *ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHello proto.InternalMessageInfo

func (m *ClientHello) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type ClientHelloReply struct {
	GrpcHost             []byte   `protobuf:"bytes,1,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	NsbHost              []byte   `protobuf:"bytes,2,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHelloReply) Reset()         { *m = ClientHelloReply{} }
func (m *ClientHelloReply) String() string { return proto.CompactTextString(m) }
func (*ClientHelloReply) ProtoMessage()    {}
func (*ClientHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{2}
}

func (m *ClientHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHelloReply.Unmarshal(m, b)
}
func (m *ClientHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHelloReply.Marshal(b, m, deterministic)
}
func (m *ClientHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHelloReply.Merge(m, src)
}
func (m *ClientHelloReply) XXX_Size() int {
	return xxx_messageInfo_ClientHelloReply.Size(m)
}
func (m *ClientHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHelloReply proto.InternalMessageInfo

func (m *ClientHelloReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *ClientHelloReply) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type RequestComingRequest struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GrpcHost             []byte   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	NsbHost              []byte   `protobuf:"bytes,3,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestComingRequest) Reset()         { *m = RequestComingRequest{} }
func (m *RequestComingRequest) String() string { return proto.CompactTextString(m) }
func (*RequestComingRequest) ProtoMessage()    {}
func (*RequestComingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{3}
}

func (m *RequestComingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestComingRequest.Unmarshal(m, b)
}
func (m *RequestComingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestComingRequest.Marshal(b, m, deterministic)
}
func (m *RequestComingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestComingRequest.Merge(m, src)
}
func (m *RequestComingRequest) XXX_Size() int {
	return xxx_messageInfo_RequestComingRequest.Size(m)
}
func (m *RequestComingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestComingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestComingRequest proto.InternalMessageInfo

func (m *RequestComingRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *RequestComingRequest) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *RequestComingRequest) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type RequestComingReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestComingReply) Reset()         { *m = RequestComingReply{} }
func (m *RequestComingReply) String() string { return proto.CompactTextString(m) }
func (*RequestComingReply) ProtoMessage()    {}
func (*RequestComingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{4}
}

func (m *RequestComingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestComingReply.Unmarshal(m, b)
}
func (m *RequestComingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestComingReply.Marshal(b, m, deterministic)
}
func (m *RequestComingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestComingReply.Merge(m, src)
}
func (m *RequestComingReply) XXX_Size() int {
	return xxx_messageInfo_RequestComingReply.Size(m)
}
func (m *RequestComingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestComingReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestComingReply proto.InternalMessageInfo

func (m *RequestComingReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RequestGrpcServiceRequest struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGrpcServiceRequest) Reset()         { *m = RequestGrpcServiceRequest{} }
func (m *RequestGrpcServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RequestGrpcServiceRequest) ProtoMessage()    {}
func (*RequestGrpcServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{5}
}

func (m *RequestGrpcServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGrpcServiceRequest.Unmarshal(m, b)
}
func (m *RequestGrpcServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGrpcServiceRequest.Marshal(b, m, deterministic)
}
func (m *RequestGrpcServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGrpcServiceRequest.Merge(m, src)
}
func (m *RequestGrpcServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RequestGrpcServiceRequest.Size(m)
}
func (m *RequestGrpcServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGrpcServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGrpcServiceRequest proto.InternalMessageInfo

func (m *RequestGrpcServiceRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RequestGrpcServiceReply struct {
	GrpcHost             []byte   `protobuf:"bytes,1,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGrpcServiceReply) Reset()         { *m = RequestGrpcServiceReply{} }
func (m *RequestGrpcServiceReply) String() string { return proto.CompactTextString(m) }
func (*RequestGrpcServiceReply) ProtoMessage()    {}
func (*RequestGrpcServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{6}
}

func (m *RequestGrpcServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGrpcServiceReply.Unmarshal(m, b)
}
func (m *RequestGrpcServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGrpcServiceReply.Marshal(b, m, deterministic)
}
func (m *RequestGrpcServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGrpcServiceReply.Merge(m, src)
}
func (m *RequestGrpcServiceReply) XXX_Size() int {
	return xxx_messageInfo_RequestGrpcServiceReply.Size(m)
}
func (m *RequestGrpcServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGrpcServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGrpcServiceReply proto.InternalMessageInfo

func (m *RequestGrpcServiceReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

type RequestNsbServiceRequest struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestNsbServiceRequest) Reset()         { *m = RequestNsbServiceRequest{} }
func (m *RequestNsbServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RequestNsbServiceRequest) ProtoMessage()    {}
func (*RequestNsbServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{7}
}

func (m *RequestNsbServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestNsbServiceRequest.Unmarshal(m, b)
}
func (m *RequestNsbServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestNsbServiceRequest.Marshal(b, m, deterministic)
}
func (m *RequestNsbServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestNsbServiceRequest.Merge(m, src)
}
func (m *RequestNsbServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RequestNsbServiceRequest.Size(m)
}
func (m *RequestNsbServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestNsbServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestNsbServiceRequest proto.InternalMessageInfo

func (m *RequestNsbServiceRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RequestNsbServiceReply struct {
	NsbHost              []byte   `protobuf:"bytes,1,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestNsbServiceReply) Reset()         { *m = RequestNsbServiceReply{} }
func (m *RequestNsbServiceReply) String() string { return proto.CompactTextString(m) }
func (*RequestNsbServiceReply) ProtoMessage()    {}
func (*RequestNsbServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{8}
}

func (m *RequestNsbServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestNsbServiceReply.Unmarshal(m, b)
}
func (m *RequestNsbServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestNsbServiceReply.Marshal(b, m, deterministic)
}
func (m *RequestNsbServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestNsbServiceReply.Merge(m, src)
}
func (m *RequestNsbServiceReply) XXX_Size() int {
	return xxx_messageInfo_RequestNsbServiceReply.Size(m)
}
func (m *RequestNsbServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestNsbServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestNsbServiceReply proto.InternalMessageInfo

func (m *RequestNsbServiceReply) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type SessionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionListRequest) Reset()         { *m = SessionListRequest{} }
func (m *SessionListRequest) String() string { return proto.CompactTextString(m) }
func (*SessionListRequest) ProtoMessage()    {}
func (*SessionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{9}
}

func (m *SessionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListRequest.Unmarshal(m, b)
}
func (m *SessionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListRequest.Marshal(b, m, deterministic)
}
func (m *SessionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListRequest.Merge(m, src)
}
func (m *SessionListRequest) XXX_Size() int {
	return xxx_messageInfo_SessionListRequest.Size(m)
}
func (m *SessionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListRequest proto.InternalMessageInfo

type SessionListReply struct {
	SessionIds           [][]byte `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	GrpcHost             [][]byte `protobuf:"bytes,2,rep,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	DefaultNsbHost       []byte   `protobuf:"bytes,3,opt,name=default_nsb_host,json=defaultNsbHost,proto3" json:"default_nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionListReply) Reset()         { *m = SessionListReply{} }
func (m *SessionListReply) String() string { return proto.CompactTextString(m) }
func (*SessionListReply) ProtoMessage()    {}
func (*SessionListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{10}
}

func (m *SessionListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListReply.Unmarshal(m, b)
}
func (m *SessionListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListReply.Marshal(b, m, deterministic)
}
func (m *SessionListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListReply.Merge(m, src)
}
func (m *SessionListReply) XXX_Size() int {
	return xxx_messageInfo_SessionListReply.Size(m)
}
func (m *SessionListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListReply proto.InternalMessageInfo

func (m *SessionListReply) GetSessionIds() [][]byte {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func (m *SessionListReply) GetGrpcHost() [][]byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *SessionListReply) GetDefaultNsbHost() []byte {
	if m != nil {
		return m.DefaultNsbHost
	}
	return nil
}

type TransactionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionListRequest) Reset()         { *m = TransactionListRequest{} }
func (m *TransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionListRequest) ProtoMessage()    {}
func (*TransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{11}
}

func (m *TransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListRequest.Unmarshal(m, b)
}
func (m *TransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListRequest.Marshal(b, m, deterministic)
}
func (m *TransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListRequest.Merge(m, src)
}
func (m *TransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionListRequest.Size(m)
}
func (m *TransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListRequest proto.InternalMessageInfo

type TransactionListReply struct {
	// with help info
	Transactions         [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	GrpcHost             [][]byte `protobuf:"bytes,2,rep,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	DefaultNsbHost       []byte   `protobuf:"bytes,3,opt,name=default_nsb_host,json=defaultNsbHost,proto3" json:"default_nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionListReply) Reset()         { *m = TransactionListReply{} }
func (m *TransactionListReply) String() string { return proto.CompactTextString(m) }
func (*TransactionListReply) ProtoMessage()    {}
func (*TransactionListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{12}
}

func (m *TransactionListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListReply.Unmarshal(m, b)
}
func (m *TransactionListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListReply.Marshal(b, m, deterministic)
}
func (m *TransactionListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListReply.Merge(m, src)
}
func (m *TransactionListReply) XXX_Size() int {
	return xxx_messageInfo_TransactionListReply.Size(m)
}
func (m *TransactionListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListReply proto.InternalMessageInfo

func (m *TransactionListReply) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *TransactionListReply) GetGrpcHost() [][]byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *TransactionListReply) GetDefaultNsbHost() []byte {
	if m != nil {
		return m.DefaultNsbHost
	}
	return nil
}

type Account struct {
	ChainId              uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{13}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type UserRegisterRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{14}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserRegisterReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacteristicFlag   uint64   `protobuf:"varint,2,opt,name=characteristic_flag,json=characteristicFlag,proto3" json:"characteristic_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterReply) Reset()         { *m = UserRegisterReply{} }
func (m *UserRegisterReply) String() string { return proto.CompactTextString(m) }
func (*UserRegisterReply) ProtoMessage()    {}
func (*UserRegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{15}
}

func (m *UserRegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterReply.Unmarshal(m, b)
}
func (m *UserRegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterReply.Marshal(b, m, deterministic)
}
func (m *UserRegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterReply.Merge(m, src)
}
func (m *UserRegisterReply) XXX_Size() int {
	return xxx_messageInfo_UserRegisterReply.Size(m)
}
func (m *UserRegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterReply proto.InternalMessageInfo

func (m *UserRegisterReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UserRegisterReply) GetCharacteristicFlag() uint64 {
	if m != nil {
		return m.CharacteristicFlag
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*ClientHello)(nil), "ClientHello")
	proto.RegisterType((*ClientHelloReply)(nil), "ClientHelloReply")
	proto.RegisterType((*RequestComingRequest)(nil), "RequestComingRequest")
	proto.RegisterType((*RequestComingReply)(nil), "RequestComingReply")
	proto.RegisterType((*RequestGrpcServiceRequest)(nil), "RequestGrpcServiceRequest")
	proto.RegisterType((*RequestGrpcServiceReply)(nil), "RequestGrpcServiceReply")
	proto.RegisterType((*RequestNsbServiceRequest)(nil), "RequestNsbServiceRequest")
	proto.RegisterType((*RequestNsbServiceReply)(nil), "RequestNsbServiceReply")
	proto.RegisterType((*SessionListRequest)(nil), "SessionListRequest")
	proto.RegisterType((*SessionListReply)(nil), "SessionListReply")
	proto.RegisterType((*TransactionListRequest)(nil), "TransactionListRequest")
	proto.RegisterType((*TransactionListReply)(nil), "TransactionListReply")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*UserRegisterRequest)(nil), "UserRegisterRequest")
	proto.RegisterType((*UserRegisterReply)(nil), "UserRegisterReply")
}

func init() { proto.RegisterFile("wsrpc.proto", fileDescriptor_b2e2d651803ed170) }

var fileDescriptor_b2e2d651803ed170 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x8f, 0x12, 0x31,
	0x14, 0x0e, 0xc3, 0xc6, 0x81, 0x07, 0x21, 0xd8, 0x25, 0xeb, 0xac, 0xc6, 0xb8, 0x36, 0x1e, 0x38,
	0xb1, 0x89, 0x9b, 0x78, 0x34, 0x31, 0x9b, 0xe8, 0x62, 0x94, 0x43, 0x77, 0xf5, 0x4a, 0x4a, 0xa7,
	0x0c, 0xcd, 0x0e, 0xed, 0xd8, 0x57, 0x34, 0x7a, 0xf3, 0x3f, 0x37, 0xed, 0x14, 0x76, 0x07, 0x89,
	0x7a, 0xf0, 0x44, 0xdf, 0xf7, 0x7e, 0x7c, 0x5f, 0xbf, 0x3e, 0x06, 0x7a, 0xdf, 0xd0, 0x56, 0x62,
	0x52, 0x59, 0xe3, 0x0c, 0x9d, 0x42, 0xfa, 0x51, 0x22, 0xf2, 0x42, 0x92, 0xc7, 0xd0, 0x11, 0x46,
	0x3b, 0xa9, 0x1d, 0x66, 0xad, 0xb3, 0xd6, 0xb8, 0xcb, 0x76, 0x31, 0x21, 0x70, 0xb4, 0xb4, 0x66,
	0x9d, 0x25, 0x67, 0xad, 0x71, 0x9f, 0x85, 0x33, 0x19, 0x40, 0xe2, 0x4c, 0xd6, 0x0e, 0x48, 0xe2,
	0x0c, 0x7d, 0x0e, 0xbd, 0xcb, 0x52, 0x49, 0xed, 0xae, 0x64, 0x59, 0x1a, 0xdf, 0xa2, 0xf9, 0x5a,
	0x86, 0x51, 0x7d, 0x16, 0xce, 0xf4, 0x3d, 0x0c, 0xef, 0x95, 0x30, 0x59, 0x95, 0xdf, 0xc9, 0x13,
	0xe8, 0x16, 0xb6, 0x12, 0xf3, 0x95, 0x41, 0x17, 0x8b, 0x3b, 0x1e, 0xb8, 0x32, 0xe8, 0xc8, 0x29,
	0x74, 0x34, 0x2e, 0xea, 0x5c, 0xcd, 0x9d, 0x6a, 0x5c, 0xf8, 0x14, 0x5d, 0xc3, 0x88, 0xc9, 0x2f,
	0x1b, 0x89, 0xee, 0xd2, 0xac, 0x95, 0x2e, 0x62, 0x40, 0x9e, 0x02, 0xa0, 0x44, 0x54, 0x46, 0xcf,
	0x55, 0x1e, 0x07, 0x76, 0x23, 0x32, 0xcd, 0x9b, 0x74, 0xc9, 0x1f, 0xe8, 0xda, 0x4d, 0xba, 0x17,
	0x40, 0xf6, 0xe8, 0xbc, 0xf8, 0x01, 0x24, 0xe6, 0x36, 0x90, 0x74, 0x58, 0x62, 0x6e, 0xe9, 0x39,
	0x9c, 0xc6, 0xaa, 0x77, 0xb6, 0x12, 0xd7, 0xd2, 0x7e, 0x55, 0x42, 0x6e, 0x95, 0x1d, 0x72, 0xe4,
	0x15, 0x3c, 0x3a, 0xd4, 0xf0, 0x37, 0x63, 0xe8, 0x04, 0xb2, 0xd8, 0x37, 0xc3, 0xc5, 0x3f, 0xf0,
	0x5c, 0xc0, 0xc9, 0x81, 0x7a, 0x4f, 0x73, 0xff, 0xce, 0xad, 0xe6, 0x9d, 0x47, 0x40, 0xae, 0x6b,
	0xe3, 0x3e, 0x28, 0x74, 0xb1, 0x9f, 0xfe, 0x80, 0x61, 0x03, 0xf5, 0x43, 0x9e, 0x41, 0xef, 0xce,
	0x74, 0xbf, 0x3e, 0xed, 0x71, 0x9f, 0xc1, 0xce, 0x75, 0xdc, 0xb7, 0xbd, 0xdd, 0xb0, 0x7d, 0x0c,
	0xc3, 0x5c, 0x2e, 0xf9, 0xa6, 0x74, 0xf3, 0x3d, 0xfb, 0x07, 0x11, 0x9f, 0x45, 0x45, 0x19, 0x9c,
	0xdc, 0x58, 0xae, 0x91, 0x0b, 0xb7, 0xa7, 0xea, 0x67, 0x0b, 0x46, 0xbf, 0xa5, 0xbc, 0x34, 0x0a,
	0x7d, 0x77, 0x87, 0x6f, 0xb5, 0x35, 0xb0, 0xff, 0xa5, 0xee, 0x35, 0xa4, 0x6f, 0x84, 0x30, 0x1b,
	0x1d, 0x36, 0x49, 0xac, 0xb8, 0xda, 0xed, 0xe0, 0x11, 0x4b, 0x43, 0x3c, 0xcd, 0x49, 0x06, 0x29,
	0xcf, 0x73, 0x2b, 0x11, 0xb7, 0x2b, 0x1d, 0x43, 0xfa, 0x19, 0x8e, 0x3f, 0xa1, 0xb4, 0x4c, 0x16,
	0x0a, 0x9d, 0xff, 0xad, 0xdf, 0x93, 0x42, 0xca, 0xeb, 0xb1, 0x61, 0x54, 0xef, 0x65, 0x67, 0x12,
	0x69, 0xd8, 0x36, 0xe1, 0x6f, 0xb0, 0x41, 0x69, 0xe7, 0xe1, 0xe1, 0x93, 0xfa, 0xdf, 0xeb, 0x81,
	0x99, 0x7f, 0xfc, 0x1b, 0x78, 0xd8, 0x9c, 0x7b, 0x60, 0x75, 0xc9, 0x39, 0x1c, 0x8b, 0x15, 0xb7,
	0x5c, 0x38, 0x69, 0x15, 0x3a, 0x25, 0xe6, 0xcb, 0x92, 0x17, 0x61, 0xd6, 0x11, 0x23, 0xcd, 0xd4,
	0xdb, 0x92, 0x17, 0x8b, 0x07, 0xe1, 0x0b, 0x72, 0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xe9,
	0x52, 0x0d, 0x50, 0x04, 0x00, 0x00,
}
