// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wsrpc.proto

package wsrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 1
type Message struct {
	Contents             string   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *Message) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type ClientHello struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHello) Reset()         { *m = ClientHello{} }
func (m *ClientHello) String() string { return proto.CompactTextString(m) }
func (*ClientHello) ProtoMessage()    {}
func (*ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{1}
}

func (m *ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHello.Unmarshal(m, b)
}
func (m *ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHello.Marshal(b, m, deterministic)
}
func (m *ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHello.Merge(m, src)
}
func (m *ClientHello) XXX_Size() int {
	return xxx_messageInfo_ClientHello.Size(m)
}
func (m *ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHello proto.InternalMessageInfo

func (m *ClientHello) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RequestComing struct {
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GrpcHost             []byte   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	NsbHost              []byte   `protobuf:"bytes,3,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestComing) Reset()         { *m = RequestComing{} }
func (m *RequestComing) String() string { return proto.CompactTextString(m) }
func (*RequestComing) ProtoMessage()    {}
func (*RequestComing) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{2}
}

func (m *RequestComing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestComing.Unmarshal(m, b)
}
func (m *RequestComing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestComing.Marshal(b, m, deterministic)
}
func (m *RequestComing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestComing.Merge(m, src)
}
func (m *RequestComing) XXX_Size() int {
	return xxx_messageInfo_RequestComing.Size(m)
}
func (m *RequestComing) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestComing.DiscardUnknown(m)
}

var xxx_messageInfo_RequestComing proto.InternalMessageInfo

func (m *RequestComing) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *RequestComing) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *RequestComing) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type RequestGrpcService struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGrpcService) Reset()         { *m = RequestGrpcService{} }
func (m *RequestGrpcService) String() string { return proto.CompactTextString(m) }
func (*RequestGrpcService) ProtoMessage()    {}
func (*RequestGrpcService) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{3}
}

func (m *RequestGrpcService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGrpcService.Unmarshal(m, b)
}
func (m *RequestGrpcService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGrpcService.Marshal(b, m, deterministic)
}
func (m *RequestGrpcService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGrpcService.Merge(m, src)
}
func (m *RequestGrpcService) XXX_Size() int {
	return xxx_messageInfo_RequestGrpcService.Size(m)
}
func (m *RequestGrpcService) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGrpcService.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGrpcService proto.InternalMessageInfo

func (m *RequestGrpcService) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type SessionList struct {
	SessionIds           [][]byte `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	DefaultNsbHost       []byte   `protobuf:"bytes,2,opt,name=default_nsb_host,json=defaultNsbHost,proto3" json:"default_nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionList) Reset()         { *m = SessionList{} }
func (m *SessionList) String() string { return proto.CompactTextString(m) }
func (*SessionList) ProtoMessage()    {}
func (*SessionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{4}
}

func (m *SessionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionList.Unmarshal(m, b)
}
func (m *SessionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionList.Marshal(b, m, deterministic)
}
func (m *SessionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionList.Merge(m, src)
}
func (m *SessionList) XXX_Size() int {
	return xxx_messageInfo_SessionList.Size(m)
}
func (m *SessionList) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionList.DiscardUnknown(m)
}

var xxx_messageInfo_SessionList proto.InternalMessageInfo

func (m *SessionList) GetSessionIds() [][]byte {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func (m *SessionList) GetDefaultNsbHost() []byte {
	if m != nil {
		return m.DefaultNsbHost
	}
	return nil
}

type TransactionList struct {
	// with help info
	Transactions         [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionList) Reset()         { *m = TransactionList{} }
func (m *TransactionList) String() string { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()    {}
func (*TransactionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{5}
}

func (m *TransactionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionList.Unmarshal(m, b)
}
func (m *TransactionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionList.Marshal(b, m, deterministic)
}
func (m *TransactionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionList.Merge(m, src)
}
func (m *TransactionList) XXX_Size() int {
	return xxx_messageInfo_TransactionList.Size(m)
}
func (m *TransactionList) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionList.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionList proto.InternalMessageInfo

func (m *TransactionList) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterType((*ClientHello)(nil), "ClientHello")
	proto.RegisterType((*RequestComing)(nil), "RequestComing")
	proto.RegisterType((*RequestGrpcService)(nil), "RequestGrpcService")
	proto.RegisterType((*SessionList)(nil), "SessionList")
	proto.RegisterType((*TransactionList)(nil), "TransactionList")
}

func init() { proto.RegisterFile("wsrpc.proto", fileDescriptor_b2e2d651803ed170) }

var fileDescriptor_b2e2d651803ed170 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0x86, 0xd3, 0xf6, 0xcb, 0x57, 0x18, 0xb0, 0x9a, 0x3d, 0xa1, 0xc6, 0x58, 0x39, 0x71, 0xf2,
	0x62, 0xfc, 0x05, 0x3d, 0xd8, 0x26, 0xea, 0x81, 0x7a, 0xf0, 0x46, 0x60, 0x19, 0x70, 0x13, 0xd8,
	0xc5, 0x9d, 0xa9, 0xfe, 0x7d, 0x03, 0x6c, 0x69, 0x4c, 0xbc, 0x0d, 0xcf, 0xb0, 0xef, 0xfb, 0x64,
	0x17, 0x82, 0x6f, 0xb2, 0x9d, 0xbc, 0xef, 0xac, 0x61, 0x13, 0xef, 0x60, 0xf9, 0x82, 0x44, 0x79,
	0x8d, 0xe2, 0x0a, 0x3c, 0x69, 0x34, 0xa3, 0x66, 0x8a, 0x66, 0xeb, 0x59, 0xe2, 0xa7, 0xd3, 0xb7,
	0x10, 0xf0, 0xaf, 0xb2, 0xa6, 0x8d, 0xe6, 0xeb, 0x59, 0x12, 0xa6, 0xc3, 0x2c, 0x56, 0x30, 0x67,
	0x13, 0x2d, 0x06, 0x32, 0x67, 0x13, 0xdf, 0x41, 0xb0, 0x69, 0x14, 0x6a, 0xde, 0x62, 0xd3, 0x98,
	0xfe, 0x88, 0xce, 0x5b, 0x1c, 0xa2, 0xc2, 0x74, 0x98, 0xe3, 0x0a, 0xce, 0x52, 0xfc, 0x3c, 0x20,
	0xf1, 0xc6, 0xb4, 0x4a, 0xd7, 0xe2, 0x06, 0x80, 0x90, 0x48, 0x19, 0x9d, 0xa9, 0xd2, 0xfd, 0xea,
	0x3b, 0xb2, 0x2b, 0xc5, 0x35, 0xf8, 0xb5, 0xed, 0x64, 0xf6, 0x61, 0x88, 0x5d, 0xb7, 0xd7, 0x83,
	0xad, 0x21, 0x16, 0x97, 0xe0, 0x69, 0x2a, 0xc6, 0xdd, 0x68, 0xb1, 0xd4, 0x54, 0xf4, 0xab, 0x38,
	0x01, 0xe1, 0x7a, 0x9e, 0x6c, 0x27, 0xf7, 0x68, 0xbf, 0x94, 0xc4, 0x3f, 0x8d, 0xde, 0x21, 0xd8,
	0x8f, 0x75, 0xcf, 0x8a, 0x58, 0xdc, 0x42, 0x70, 0xf2, 0xe9, 0xaf, 0x61, 0x91, 0x84, 0x29, 0x4c,
	0x42, 0x24, 0x12, 0xb8, 0x28, 0xb1, 0xca, 0x0f, 0x0d, 0x67, 0x53, 0xf9, 0x28, 0xb6, 0x72, 0xfc,
	0xd5, 0x39, 0x3c, 0xc2, 0xf9, 0x9b, 0xcd, 0x35, 0xe5, 0x92, 0x8f, 0xe9, 0x31, 0x84, 0x7c, 0x42,
	0xc7, 0xf8, 0x5f, 0xac, 0xf8, 0x3f, 0xbc, 0xcb, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04,
	0x6f, 0x74, 0xba, 0xa6, 0x01, 0x00, 0x00,
}
