// Code generated by protoc-gen-go. DO NOT EDIT.
// source: uiprpc.proto

package uiprpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpIntents struct {
	Contents             [][]byte `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Dependencies         [][]byte `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpIntents) Reset()         { *m = OpIntents{} }
func (m *OpIntents) String() string { return proto.CompactTextString(m) }
func (*OpIntents) ProtoMessage()    {}
func (*OpIntents) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{0}
}

func (m *OpIntents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpIntents.Unmarshal(m, b)
}
func (m *OpIntents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpIntents.Marshal(b, m, deterministic)
}
func (m *OpIntents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpIntents.Merge(m, src)
}
func (m *OpIntents) XXX_Size() int {
	return xxx_messageInfo_OpIntents.Size(m)
}
func (m *OpIntents) XXX_DiscardUnknown() {
	xxx_messageInfo_OpIntents.DiscardUnknown(m)
}

var xxx_messageInfo_OpIntents proto.InternalMessageInfo

func (m *OpIntents) GetContents() [][]byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *OpIntents) GetDependencies() [][]byte {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type Transaction struct {
	ChainType            uint32   `protobuf:"varint,1,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	Src                  []byte   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  []byte   `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Domain               []byte   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Meta                 []byte   `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetChainType() uint32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *Transaction) GetSrc() []byte {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Transaction) GetDst() []byte {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Transaction) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *Transaction) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Signature struct {
	SignatureType        uint32   `protobuf:"varint,1,opt,name=signature_type,json=signatureType,proto3" json:"signature_type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{2}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignatureType() uint32 {
	if m != nil {
		return m.SignatureType
	}
	return 0
}

func (m *Signature) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Account struct {
	ChainType            uint32   `protobuf:"varint,1,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{3}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetChainType() uint32 {
	if m != nil {
		return m.ChainType
	}
	return 0
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Attestation struct {
	Tid                  uint32       `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Content              []byte       `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Signature            []*Signature `protobuf:"bytes,3,rep,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{4}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetTid() uint32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Attestation) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Attestation) GetSignature() []*Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type UserRegisterRequest struct {
	User                 *Account `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{5}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetUser() *Account {
	if m != nil {
		return m.User
	}
	return nil
}

type UserRegisterReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterReply) Reset()         { *m = UserRegisterReply{} }
func (m *UserRegisterReply) String() string { return proto.CompactTextString(m) }
func (*UserRegisterReply) ProtoMessage()    {}
func (*UserRegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{6}
}

func (m *UserRegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterReply.Unmarshal(m, b)
}
func (m *UserRegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterReply.Marshal(b, m, deterministic)
}
func (m *UserRegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterReply.Merge(m, src)
}
func (m *UserRegisterReply) XXX_Size() int {
	return xxx_messageInfo_UserRegisterReply.Size(m)
}
func (m *UserRegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterReply proto.InternalMessageInfo

func (m *UserRegisterReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionStartRequest struct {
	Opintents            *OpIntents `protobuf:"bytes,1,opt,name=opintents,proto3" json:"opintents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SessionStartRequest) Reset()         { *m = SessionStartRequest{} }
func (m *SessionStartRequest) String() string { return proto.CompactTextString(m) }
func (*SessionStartRequest) ProtoMessage()    {}
func (*SessionStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{7}
}

func (m *SessionStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStartRequest.Unmarshal(m, b)
}
func (m *SessionStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStartRequest.Marshal(b, m, deterministic)
}
func (m *SessionStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStartRequest.Merge(m, src)
}
func (m *SessionStartRequest) XXX_Size() int {
	return xxx_messageInfo_SessionStartRequest.Size(m)
}
func (m *SessionStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStartRequest proto.InternalMessageInfo

func (m *SessionStartRequest) GetOpintents() *OpIntents {
	if m != nil {
		return m.Opintents
	}
	return nil
}

type SessionStartReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionStartReply) Reset()         { *m = SessionStartReply{} }
func (m *SessionStartReply) String() string { return proto.CompactTextString(m) }
func (*SessionStartReply) ProtoMessage()    {}
func (*SessionStartReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{8}
}

func (m *SessionStartReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionStartReply.Unmarshal(m, b)
}
func (m *SessionStartReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionStartReply.Marshal(b, m, deterministic)
}
func (m *SessionStartReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionStartReply.Merge(m, src)
}
func (m *SessionStartReply) XXX_Size() int {
	return xxx_messageInfo_SessionStartReply.Size(m)
}
func (m *SessionStartReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionStartReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionStartReply proto.InternalMessageInfo

func (m *SessionStartReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionAckForInitRequest struct {
	// isc_address
	SessionId            []byte     `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	User                 *Account   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UserSignature        *Signature `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SessionAckForInitRequest) Reset()         { *m = SessionAckForInitRequest{} }
func (m *SessionAckForInitRequest) String() string { return proto.CompactTextString(m) }
func (*SessionAckForInitRequest) ProtoMessage()    {}
func (*SessionAckForInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{9}
}

func (m *SessionAckForInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAckForInitRequest.Unmarshal(m, b)
}
func (m *SessionAckForInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAckForInitRequest.Marshal(b, m, deterministic)
}
func (m *SessionAckForInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAckForInitRequest.Merge(m, src)
}
func (m *SessionAckForInitRequest) XXX_Size() int {
	return xxx_messageInfo_SessionAckForInitRequest.Size(m)
}
func (m *SessionAckForInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAckForInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAckForInitRequest proto.InternalMessageInfo

func (m *SessionAckForInitRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionAckForInitRequest) GetUser() *Account {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SessionAckForInitRequest) GetUserSignature() *Signature {
	if m != nil {
		return m.UserSignature
	}
	return nil
}

type SessionAckForInitReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionAckForInitReply) Reset()         { *m = SessionAckForInitReply{} }
func (m *SessionAckForInitReply) String() string { return proto.CompactTextString(m) }
func (*SessionAckForInitReply) ProtoMessage()    {}
func (*SessionAckForInitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{10}
}

func (m *SessionAckForInitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionAckForInitReply.Unmarshal(m, b)
}
func (m *SessionAckForInitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionAckForInitReply.Marshal(b, m, deterministic)
}
func (m *SessionAckForInitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionAckForInitReply.Merge(m, src)
}
func (m *SessionAckForInitReply) XXX_Size() int {
	return xxx_messageInfo_SessionAckForInitReply.Size(m)
}
func (m *SessionAckForInitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionAckForInitReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionAckForInitReply proto.InternalMessageInfo

func (m *SessionAckForInitReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionFinishedRequest struct {
	// isc_address
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IscState             uint32   `protobuf:"varint,2,opt,name=isc_state,json=iscState,proto3" json:"isc_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionFinishedRequest) Reset()         { *m = SessionFinishedRequest{} }
func (m *SessionFinishedRequest) String() string { return proto.CompactTextString(m) }
func (*SessionFinishedRequest) ProtoMessage()    {}
func (*SessionFinishedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{11}
}

func (m *SessionFinishedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionFinishedRequest.Unmarshal(m, b)
}
func (m *SessionFinishedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionFinishedRequest.Marshal(b, m, deterministic)
}
func (m *SessionFinishedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionFinishedRequest.Merge(m, src)
}
func (m *SessionFinishedRequest) XXX_Size() int {
	return xxx_messageInfo_SessionFinishedRequest.Size(m)
}
func (m *SessionFinishedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionFinishedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionFinishedRequest proto.InternalMessageInfo

func (m *SessionFinishedRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionFinishedRequest) GetIscState() uint32 {
	if m != nil {
		return m.IscState
	}
	return 0
}

type SessionFinishedReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionFinishedReply) Reset()         { *m = SessionFinishedReply{} }
func (m *SessionFinishedReply) String() string { return proto.CompactTextString(m) }
func (*SessionFinishedReply) ProtoMessage()    {}
func (*SessionFinishedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{12}
}

func (m *SessionFinishedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionFinishedReply.Unmarshal(m, b)
}
func (m *SessionFinishedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionFinishedReply.Marshal(b, m, deterministic)
}
func (m *SessionFinishedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionFinishedReply.Merge(m, src)
}
func (m *SessionFinishedReply) XXX_Size() int {
	return xxx_messageInfo_SessionFinishedReply.Size(m)
}
func (m *SessionFinishedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionFinishedReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionFinishedReply proto.InternalMessageInfo

func (m *SessionFinishedReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionRequestForInitRequest struct {
	// isc_address
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IscState             uint32   `protobuf:"varint,2,opt,name=isc_state,json=iscState,proto3" json:"isc_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequestForInitRequest) Reset()         { *m = SessionRequestForInitRequest{} }
func (m *SessionRequestForInitRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequestForInitRequest) ProtoMessage()    {}
func (*SessionRequestForInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{13}
}

func (m *SessionRequestForInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequestForInitRequest.Unmarshal(m, b)
}
func (m *SessionRequestForInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequestForInitRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequestForInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequestForInitRequest.Merge(m, src)
}
func (m *SessionRequestForInitRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequestForInitRequest.Size(m)
}
func (m *SessionRequestForInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequestForInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequestForInitRequest proto.InternalMessageInfo

func (m *SessionRequestForInitRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionRequestForInitRequest) GetIscState() uint32 {
	if m != nil {
		return m.IscState
	}
	return 0
}

type SessionRequestForInitReply struct {
	Opintents            [][]byte `protobuf:"bytes,1,rep,name=opintents,proto3" json:"opintents,omitempty"`
	Dependencies         [][]byte `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequestForInitReply) Reset()         { *m = SessionRequestForInitReply{} }
func (m *SessionRequestForInitReply) String() string { return proto.CompactTextString(m) }
func (*SessionRequestForInitReply) ProtoMessage()    {}
func (*SessionRequestForInitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{14}
}

func (m *SessionRequestForInitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequestForInitReply.Unmarshal(m, b)
}
func (m *SessionRequestForInitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequestForInitReply.Marshal(b, m, deterministic)
}
func (m *SessionRequestForInitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequestForInitReply.Merge(m, src)
}
func (m *SessionRequestForInitReply) XXX_Size() int {
	return xxx_messageInfo_SessionRequestForInitReply.Size(m)
}
func (m *SessionRequestForInitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequestForInitReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequestForInitReply proto.InternalMessageInfo

func (m *SessionRequestForInitReply) GetOpintents() [][]byte {
	if m != nil {
		return m.Opintents
	}
	return nil
}

func (m *SessionRequestForInitReply) GetDependencies() [][]byte {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type SessionRequireTransactRequest struct {
	// isc_address
	SessionId            []byte       `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SessionRequireTransactRequest) Reset()         { *m = SessionRequireTransactRequest{} }
func (m *SessionRequireTransactRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequireTransactRequest) ProtoMessage()    {}
func (*SessionRequireTransactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{15}
}

func (m *SessionRequireTransactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequireTransactRequest.Unmarshal(m, b)
}
func (m *SessionRequireTransactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequireTransactRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequireTransactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequireTransactRequest.Merge(m, src)
}
func (m *SessionRequireTransactRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequireTransactRequest.Size(m)
}
func (m *SessionRequireTransactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequireTransactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequireTransactRequest proto.InternalMessageInfo

func (m *SessionRequireTransactRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionRequireTransactRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type SessionRequireTransactReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequireTransactReply) Reset()         { *m = SessionRequireTransactReply{} }
func (m *SessionRequireTransactReply) String() string { return proto.CompactTextString(m) }
func (*SessionRequireTransactReply) ProtoMessage()    {}
func (*SessionRequireTransactReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{16}
}

func (m *SessionRequireTransactReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequireTransactReply.Unmarshal(m, b)
}
func (m *SessionRequireTransactReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequireTransactReply.Marshal(b, m, deterministic)
}
func (m *SessionRequireTransactReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequireTransactReply.Merge(m, src)
}
func (m *SessionRequireTransactReply) XXX_Size() int {
	return xxx_messageInfo_SessionRequireTransactReply.Size(m)
}
func (m *SessionRequireTransactReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequireTransactReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequireTransactReply proto.InternalMessageInfo

func (m *SessionRequireTransactReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AttestationReceiveRequest struct {
	// isc_address
	SessionId            []byte       `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Atte                 *Attestation `protobuf:"bytes,2,opt,name=atte,proto3" json:"atte,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AttestationReceiveRequest) Reset()         { *m = AttestationReceiveRequest{} }
func (m *AttestationReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*AttestationReceiveRequest) ProtoMessage()    {}
func (*AttestationReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{17}
}

func (m *AttestationReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationReceiveRequest.Unmarshal(m, b)
}
func (m *AttestationReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationReceiveRequest.Marshal(b, m, deterministic)
}
func (m *AttestationReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationReceiveRequest.Merge(m, src)
}
func (m *AttestationReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_AttestationReceiveRequest.Size(m)
}
func (m *AttestationReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationReceiveRequest proto.InternalMessageInfo

func (m *AttestationReceiveRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *AttestationReceiveRequest) GetAtte() *Attestation {
	if m != nil {
		return m.Atte
	}
	return nil
}

type AttestationReceiveReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationReceiveReply) Reset()         { *m = AttestationReceiveReply{} }
func (m *AttestationReceiveReply) String() string { return proto.CompactTextString(m) }
func (*AttestationReceiveReply) ProtoMessage()    {}
func (*AttestationReceiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_65695cb26327d0ea, []int{18}
}

func (m *AttestationReceiveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationReceiveReply.Unmarshal(m, b)
}
func (m *AttestationReceiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationReceiveReply.Marshal(b, m, deterministic)
}
func (m *AttestationReceiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationReceiveReply.Merge(m, src)
}
func (m *AttestationReceiveReply) XXX_Size() int {
	return xxx_messageInfo_AttestationReceiveReply.Size(m)
}
func (m *AttestationReceiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationReceiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationReceiveReply proto.InternalMessageInfo

func (m *AttestationReceiveReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*OpIntents)(nil), "OpIntents")
	proto.RegisterType((*Transaction)(nil), "Transaction")
	proto.RegisterType((*Signature)(nil), "Signature")
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*Attestation)(nil), "Attestation")
	proto.RegisterType((*UserRegisterRequest)(nil), "UserRegisterRequest")
	proto.RegisterType((*UserRegisterReply)(nil), "UserRegisterReply")
	proto.RegisterType((*SessionStartRequest)(nil), "SessionStartRequest")
	proto.RegisterType((*SessionStartReply)(nil), "SessionStartReply")
	proto.RegisterType((*SessionAckForInitRequest)(nil), "SessionAckForInitRequest")
	proto.RegisterType((*SessionAckForInitReply)(nil), "SessionAckForInitReply")
	proto.RegisterType((*SessionFinishedRequest)(nil), "SessionFinishedRequest")
	proto.RegisterType((*SessionFinishedReply)(nil), "SessionFinishedReply")
	proto.RegisterType((*SessionRequestForInitRequest)(nil), "SessionRequestForInitRequest")
	proto.RegisterType((*SessionRequestForInitReply)(nil), "SessionRequestForInitReply")
	proto.RegisterType((*SessionRequireTransactRequest)(nil), "SessionRequireTransactRequest")
	proto.RegisterType((*SessionRequireTransactReply)(nil), "SessionRequireTransactReply")
	proto.RegisterType((*AttestationReceiveRequest)(nil), "AttestationReceiveRequest")
	proto.RegisterType((*AttestationReceiveReply)(nil), "AttestationReceiveReply")
}

func init() { proto.RegisterFile("uiprpc.proto", fileDescriptor_65695cb26327d0ea) }

var fileDescriptor_65695cb26327d0ea = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0x92, 0xb2, 0x35, 0xa7, 0xe9, 0x18, 0xde, 0x5f, 0x96, 0xb5, 0xa8, 0x0a, 0x02, 0x85,
	0x0b, 0x2c, 0xd1, 0xdd, 0xec, 0x0e, 0x15, 0xc1, 0xd0, 0x00, 0x09, 0x29, 0x1d, 0xbb, 0x40, 0x13,
	0x55, 0x48, 0xac, 0xcd, 0x1a, 0x73, 0x42, 0xec, 0xa2, 0x4d, 0xe2, 0x09, 0x78, 0x2c, 0x1e, 0x86,
	0xe7, 0x40, 0xf1, 0x5c, 0x37, 0x6d, 0x93, 0x52, 0x2e, 0xb9, 0xaa, 0xcf, 0xb1, 0xf3, 0x9d, 0xef,
	0x7c, 0xc7, 0x9f, 0x55, 0x70, 0xc6, 0x34, 0xcb, 0xb3, 0x18, 0x67, 0x79, 0x2a, 0x52, 0xff, 0x1d,
	0xd8, 0x1f, 0xb2, 0x13, 0x26, 0x08, 0x13, 0x1c, 0x79, 0xd0, 0x8c, 0xd3, 0xbb, 0xb5, 0x6b, 0xf4,
	0xac, 0xc0, 0x09, 0x75, 0x8c, 0x7c, 0x70, 0x12, 0x92, 0x11, 0x96, 0x10, 0x16, 0x53, 0xc2, 0x5d,
	0x53, 0xee, 0xcf, 0xe4, 0xfc, 0x1f, 0xd0, 0x3a, 0xcd, 0x23, 0xc6, 0xa3, 0x58, 0xd0, 0x94, 0xa1,
	0x2e, 0x40, 0x7c, 0x19, 0x51, 0x36, 0x12, 0xb7, 0x19, 0x71, 0x8d, 0x9e, 0x11, 0xb4, 0x43, 0x5b,
	0x66, 0x4e, 0x6f, 0x33, 0x82, 0x36, 0xc1, 0xe2, 0x79, 0xec, 0x9a, 0x3d, 0x23, 0x70, 0xc2, 0x62,
	0x59, 0x64, 0x12, 0x2e, 0x5c, 0xeb, 0x2e, 0x93, 0x70, 0x81, 0x76, 0x61, 0x2d, 0x49, 0xaf, 0x23,
	0xca, 0xdc, 0x86, 0x4c, 0xaa, 0x08, 0x21, 0x68, 0x5c, 0x13, 0x11, 0xb9, 0xf7, 0x64, 0x56, 0xae,
	0xfd, 0xf7, 0x60, 0x0f, 0xe9, 0x05, 0x8b, 0xc4, 0x38, 0x27, 0xe8, 0x31, 0x6c, 0xf0, 0x49, 0x50,
	0xae, 0xdf, 0xd6, 0x59, 0xc9, 0xc1, 0x85, 0x75, 0xd5, 0xa1, 0xe2, 0x31, 0x09, 0xfd, 0x97, 0xb0,
	0x3e, 0x88, 0xe3, 0x74, 0xcc, 0xc4, 0xdf, 0xfa, 0x70, 0x61, 0x3d, 0x4a, 0x92, 0x9c, 0x70, 0x3e,
	0xc1, 0x50, 0xa1, 0x1f, 0x43, 0x6b, 0x20, 0x04, 0xe1, 0x22, 0x92, 0x7a, 0x6c, 0x82, 0x25, 0x68,
	0xa2, 0x00, 0x8a, 0x65, 0x7d, 0x79, 0x14, 0x80, 0xad, 0x99, 0xba, 0x56, 0xcf, 0x0a, 0x5a, 0x7d,
	0xc0, 0xba, 0xbd, 0x70, 0xba, 0xe9, 0x1f, 0xc2, 0xd6, 0x47, 0x4e, 0xf2, 0x90, 0x5c, 0x50, 0x2e,
	0x8a, 0xdf, 0x6f, 0x63, 0xc2, 0x05, 0xea, 0x40, 0x63, 0xcc, 0x49, 0x2e, 0xab, 0xb5, 0xfa, 0x4d,
	0xac, 0x9a, 0x09, 0x65, 0xd6, 0x7f, 0x04, 0x0f, 0x66, 0x3f, 0xca, 0xbe, 0xde, 0xa2, 0x0d, 0x30,
	0xd3, 0x2b, 0xf9, 0x41, 0x33, 0x34, 0xd3, 0x2b, 0xff, 0x05, 0x6c, 0x0d, 0x09, 0xe7, 0x34, 0x65,
	0x43, 0x11, 0xe5, 0x62, 0x82, 0x1c, 0x80, 0x9d, 0x66, 0x54, 0x5f, 0x13, 0x43, 0x52, 0xd3, 0x97,
	0x28, 0x9c, 0x6e, 0x16, 0x55, 0x66, 0x01, 0xaa, 0xaa, 0xfc, 0x34, 0xc0, 0x55, 0xa7, 0x06, 0xf1,
	0xd5, 0x71, 0x9a, 0x9f, 0x30, 0xaa, 0x6b, 0x75, 0x01, 0xf8, 0xdd, 0xde, 0x48, 0x29, 0xe7, 0x84,
	0xb6, 0xca, 0x9c, 0x24, 0xba, 0x49, 0xb3, 0xaa, 0x49, 0xf4, 0x1c, 0x36, 0x8a, 0xdf, 0x51, 0x59,
	0x48, 0x63, 0x4e, 0xc8, 0x76, 0x71, 0x42, 0x87, 0x7e, 0x00, 0xbb, 0x15, 0x5c, 0xaa, 0x68, 0x9f,
	0xea, 0x93, 0xc7, 0x94, 0x51, 0x7e, 0x49, 0x92, 0x15, 0x39, 0x1f, 0x80, 0x4d, 0x79, 0x3c, 0x2a,
	0x2e, 0x05, 0x91, 0xc4, 0xdb, 0x61, 0x93, 0xf2, 0x78, 0x58, 0xc4, 0xfe, 0x13, 0xd8, 0x5e, 0x40,
	0xad, 0xaa, 0xfe, 0x09, 0x3a, 0xea, 0x9c, 0xaa, 0xfa, 0x6f, 0xba, 0x2d, 0xe5, 0xf0, 0x19, 0xbc,
	0x1a, 0xec, 0x82, 0x49, 0x67, 0x76, 0xfa, 0xc5, 0x23, 0x30, 0x4d, 0xac, 0xf4, 0x4a, 0x9c, 0x43,
	0xb7, 0x84, 0x4f, 0x73, 0x32, 0x79, 0x33, 0x56, 0x1e, 0xba, 0x29, 0x6e, 0xd4, 0xc8, 0x1d, 0x5c,
	0x7a, 0x70, 0x42, 0x53, 0xdc, 0xf8, 0xcf, 0xe0, 0xa0, 0x0e, 0xbd, 0x4a, 0xc8, 0x73, 0xd8, 0x2f,
	0x59, 0x34, 0x24, 0x31, 0xa1, 0xdf, 0xc9, 0x8a, 0x44, 0x7a, 0xd0, 0x88, 0x84, 0x12, 0xb0, 0xa0,
	0x52, 0x06, 0x92, 0x3b, 0xfe, 0x53, 0xd8, 0xab, 0x42, 0xaf, 0x20, 0xd2, 0xff, 0x6d, 0x82, 0x75,
	0xf6, 0x7a, 0x88, 0x8e, 0xc0, 0x29, 0x3b, 0x13, 0x6d, 0xe3, 0x0a, 0x77, 0x7b, 0x08, 0x2f, 0xda,
	0xf7, 0x08, 0x9c, 0xb2, 0xdb, 0xd0, 0x36, 0xae, 0x70, 0xaf, 0x87, 0xf0, 0xa2, 0x25, 0xdf, 0x68,
	0x9f, 0x4e, 0x6f, 0x3d, 0xda, 0xc7, 0x75, 0xae, 0xf4, 0xf6, 0x70, 0x8d, 0x49, 0xce, 0xb4, 0x29,
	0xe6, 0xc4, 0x47, 0x0f, 0xf1, 0xd2, 0x99, 0x7b, 0x1d, 0xbc, 0x6c, 0x6a, 0x6f, 0x01, 0x2d, 0xea,
	0x88, 0x3c, 0x5c, 0x3b, 0x3a, 0xcf, 0xc5, 0x35, 0xc2, 0xf7, 0x7f, 0x99, 0xd0, 0x78, 0x35, 0xc8,
	0x32, 0x34, 0x80, 0xfb, 0x73, 0x5e, 0x43, 0xba, 0xb1, 0x39, 0x4f, 0x7b, 0x3b, 0xb8, 0xd2, 0x96,
	0x43, 0xd8, 0xa9, 0xb4, 0x0a, 0xea, 0xe2, 0x65, 0xf6, 0xf4, 0x0e, 0xf0, 0x12, 0x87, 0xfd, 0x07,
	0x22, 0x7e, 0x59, 0x93, 0xff, 0x1e, 0x0e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x49, 0x09, 0x20,
	0xac, 0x4d, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VESClient is the client API for VES service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VESClient interface {
	UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterReply, error)
	SessionStart(ctx context.Context, in *SessionStartRequest, opts ...grpc.CallOption) (*SessionStartReply, error)
	SessionAckForInit(ctx context.Context, in *SessionAckForInitRequest, opts ...grpc.CallOption) (*SessionAckForInitReply, error)
	SessionRequireTransact(ctx context.Context, in *SessionRequireTransactRequest, opts ...grpc.CallOption) (*SessionRequireTransactReply, error)
	AttestationReceive(ctx context.Context, in *AttestationReceiveRequest, opts ...grpc.CallOption) (*AttestationReceiveReply, error)
}

type vESClient struct {
	cc *grpc.ClientConn
}

func NewVESClient(cc *grpc.ClientConn) VESClient {
	return &vESClient{cc}
}

func (c *vESClient) UserRegister(ctx context.Context, in *UserRegisterRequest, opts ...grpc.CallOption) (*UserRegisterReply, error) {
	out := new(UserRegisterReply)
	err := c.cc.Invoke(ctx, "/VES/UserRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vESClient) SessionStart(ctx context.Context, in *SessionStartRequest, opts ...grpc.CallOption) (*SessionStartReply, error) {
	out := new(SessionStartReply)
	err := c.cc.Invoke(ctx, "/VES/SessionStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vESClient) SessionAckForInit(ctx context.Context, in *SessionAckForInitRequest, opts ...grpc.CallOption) (*SessionAckForInitReply, error) {
	out := new(SessionAckForInitReply)
	err := c.cc.Invoke(ctx, "/VES/SessionAckForInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vESClient) SessionRequireTransact(ctx context.Context, in *SessionRequireTransactRequest, opts ...grpc.CallOption) (*SessionRequireTransactReply, error) {
	out := new(SessionRequireTransactReply)
	err := c.cc.Invoke(ctx, "/VES/SessionRequireTransact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vESClient) AttestationReceive(ctx context.Context, in *AttestationReceiveRequest, opts ...grpc.CallOption) (*AttestationReceiveReply, error) {
	out := new(AttestationReceiveReply)
	err := c.cc.Invoke(ctx, "/VES/AttestationReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VESServer is the server API for VES service.
type VESServer interface {
	UserRegister(context.Context, *UserRegisterRequest) (*UserRegisterReply, error)
	SessionStart(context.Context, *SessionStartRequest) (*SessionStartReply, error)
	SessionAckForInit(context.Context, *SessionAckForInitRequest) (*SessionAckForInitReply, error)
	SessionRequireTransact(context.Context, *SessionRequireTransactRequest) (*SessionRequireTransactReply, error)
	AttestationReceive(context.Context, *AttestationReceiveRequest) (*AttestationReceiveReply, error)
}

func RegisterVESServer(s *grpc.Server, srv VESServer) {
	s.RegisterService(&_VES_serviceDesc, srv)
}

func _VES_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VESServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VES/UserRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VESServer).UserRegister(ctx, req.(*UserRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VES_SessionStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VESServer).SessionStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VES/SessionStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VESServer).SessionStart(ctx, req.(*SessionStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VES_SessionAckForInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionAckForInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VESServer).SessionAckForInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VES/SessionAckForInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VESServer).SessionAckForInit(ctx, req.(*SessionAckForInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VES_SessionRequireTransact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequireTransactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VESServer).SessionRequireTransact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VES/SessionRequireTransact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VESServer).SessionRequireTransact(ctx, req.(*SessionRequireTransactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VES_AttestationReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VESServer).AttestationReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VES/AttestationReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VESServer).AttestationReceive(ctx, req.(*AttestationReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VES_serviceDesc = grpc.ServiceDesc{
	ServiceName: "VES",
	HandlerType: (*VESServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRegister",
			Handler:    _VES_UserRegister_Handler,
		},
		{
			MethodName: "SessionStart",
			Handler:    _VES_SessionStart_Handler,
		},
		{
			MethodName: "SessionAckForInit",
			Handler:    _VES_SessionAckForInit_Handler,
		},
		{
			MethodName: "SessionRequireTransact",
			Handler:    _VES_SessionRequireTransact_Handler,
		},
		{
			MethodName: "AttestationReceive",
			Handler:    _VES_AttestationReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uiprpc.proto",
}

// DAppClient is the client API for DApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DAppClient interface {
	SessionFinished(ctx context.Context, in *SessionFinishedRequest, opts ...grpc.CallOption) (*SessionFinishedReply, error)
	SessionRequestForInit(ctx context.Context, in *SessionRequestForInitRequest, opts ...grpc.CallOption) (*SessionRequestForInitReply, error)
	SessionRequireTransact(ctx context.Context, in *SessionRequireTransactRequest, opts ...grpc.CallOption) (*SessionRequireTransactReply, error)
	AttestationReceive(ctx context.Context, in *AttestationReceiveRequest, opts ...grpc.CallOption) (*AttestationReceiveReply, error)
}

type dAppClient struct {
	cc *grpc.ClientConn
}

func NewDAppClient(cc *grpc.ClientConn) DAppClient {
	return &dAppClient{cc}
}

func (c *dAppClient) SessionFinished(ctx context.Context, in *SessionFinishedRequest, opts ...grpc.CallOption) (*SessionFinishedReply, error) {
	out := new(SessionFinishedReply)
	err := c.cc.Invoke(ctx, "/DApp/SessionFinished", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAppClient) SessionRequestForInit(ctx context.Context, in *SessionRequestForInitRequest, opts ...grpc.CallOption) (*SessionRequestForInitReply, error) {
	out := new(SessionRequestForInitReply)
	err := c.cc.Invoke(ctx, "/DApp/SessionRequestForInit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAppClient) SessionRequireTransact(ctx context.Context, in *SessionRequireTransactRequest, opts ...grpc.CallOption) (*SessionRequireTransactReply, error) {
	out := new(SessionRequireTransactReply)
	err := c.cc.Invoke(ctx, "/DApp/SessionRequireTransact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dAppClient) AttestationReceive(ctx context.Context, in *AttestationReceiveRequest, opts ...grpc.CallOption) (*AttestationReceiveReply, error) {
	out := new(AttestationReceiveReply)
	err := c.cc.Invoke(ctx, "/DApp/AttestationReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DAppServer is the server API for DApp service.
type DAppServer interface {
	SessionFinished(context.Context, *SessionFinishedRequest) (*SessionFinishedReply, error)
	SessionRequestForInit(context.Context, *SessionRequestForInitRequest) (*SessionRequestForInitReply, error)
	SessionRequireTransact(context.Context, *SessionRequireTransactRequest) (*SessionRequireTransactReply, error)
	AttestationReceive(context.Context, *AttestationReceiveRequest) (*AttestationReceiveReply, error)
}

func RegisterDAppServer(s *grpc.Server, srv DAppServer) {
	s.RegisterService(&_DApp_serviceDesc, srv)
}

func _DApp_SessionFinished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionFinishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAppServer).SessionFinished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DApp/SessionFinished",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAppServer).SessionFinished(ctx, req.(*SessionFinishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DApp_SessionRequestForInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequestForInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAppServer).SessionRequestForInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DApp/SessionRequestForInit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAppServer).SessionRequestForInit(ctx, req.(*SessionRequestForInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DApp_SessionRequireTransact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequireTransactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAppServer).SessionRequireTransact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DApp/SessionRequireTransact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAppServer).SessionRequireTransact(ctx, req.(*SessionRequireTransactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DApp_AttestationReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DAppServer).AttestationReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DApp/AttestationReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DAppServer).AttestationReceive(ctx, req.(*AttestationReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DApp",
	HandlerType: (*DAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SessionFinished",
			Handler:    _DApp_SessionFinished_Handler,
		},
		{
			MethodName: "SessionRequestForInit",
			Handler:    _DApp_SessionRequestForInit_Handler,
		},
		{
			MethodName: "SessionRequireTransact",
			Handler:    _DApp_SessionRequireTransact_Handler,
		},
		{
			MethodName: "AttestationReceive",
			Handler:    _DApp_AttestationReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "uiprpc.proto",
}
