// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wsrpc.proto

package wsrpc

import (
	fmt "fmt"
	uiprpc_base "github.com/Myriad-Dreamin/go-ves/grpc/uiprpc-base"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 1
type Message struct {
	Contents             string   `protobuf:"bytes,1,opt,name=contents,proto3" json:"contents,omitempty"`
	From                 []byte   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContents() string {
	if m != nil {
		return m.Contents
	}
	return ""
}

func (m *Message) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Message) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type ClientHello struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHello) Reset()         { *m = ClientHello{} }
func (m *ClientHello) String() string { return proto.CompactTextString(m) }
func (*ClientHello) ProtoMessage()    {}
func (*ClientHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{1}
}

func (m *ClientHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHello.Unmarshal(m, b)
}
func (m *ClientHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHello.Marshal(b, m, deterministic)
}
func (m *ClientHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHello.Merge(m, src)
}
func (m *ClientHello) XXX_Size() int {
	return xxx_messageInfo_ClientHello.Size(m)
}
func (m *ClientHello) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHello.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHello proto.InternalMessageInfo

func (m *ClientHello) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type ClientHelloReply struct {
	GrpcHost             []byte   `protobuf:"bytes,1,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	NsbHost              []byte   `protobuf:"bytes,2,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientHelloReply) Reset()         { *m = ClientHelloReply{} }
func (m *ClientHelloReply) String() string { return proto.CompactTextString(m) }
func (*ClientHelloReply) ProtoMessage()    {}
func (*ClientHelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{2}
}

func (m *ClientHelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientHelloReply.Unmarshal(m, b)
}
func (m *ClientHelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientHelloReply.Marshal(b, m, deterministic)
}
func (m *ClientHelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientHelloReply.Merge(m, src)
}
func (m *ClientHelloReply) XXX_Size() int {
	return xxx_messageInfo_ClientHelloReply.Size(m)
}
func (m *ClientHelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientHelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_ClientHelloReply proto.InternalMessageInfo

func (m *ClientHelloReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *ClientHelloReply) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type RequestComingRequest struct {
	SessionId            []byte               `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Account              *uiprpc_base.Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	GrpcHost             []byte               `protobuf:"bytes,3,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	NsbHost              []byte               `protobuf:"bytes,4,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RequestComingRequest) Reset()         { *m = RequestComingRequest{} }
func (m *RequestComingRequest) String() string { return proto.CompactTextString(m) }
func (*RequestComingRequest) ProtoMessage()    {}
func (*RequestComingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{3}
}

func (m *RequestComingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestComingRequest.Unmarshal(m, b)
}
func (m *RequestComingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestComingRequest.Marshal(b, m, deterministic)
}
func (m *RequestComingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestComingRequest.Merge(m, src)
}
func (m *RequestComingRequest) XXX_Size() int {
	return xxx_messageInfo_RequestComingRequest.Size(m)
}
func (m *RequestComingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestComingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestComingRequest proto.InternalMessageInfo

func (m *RequestComingRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *RequestComingRequest) GetAccount() *uiprpc_base.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *RequestComingRequest) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *RequestComingRequest) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type RequestComingReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestComingReply) Reset()         { *m = RequestComingReply{} }
func (m *RequestComingReply) String() string { return proto.CompactTextString(m) }
func (*RequestComingReply) ProtoMessage()    {}
func (*RequestComingReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{4}
}

func (m *RequestComingReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestComingReply.Unmarshal(m, b)
}
func (m *RequestComingReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestComingReply.Marshal(b, m, deterministic)
}
func (m *RequestComingReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestComingReply.Merge(m, src)
}
func (m *RequestComingReply) XXX_Size() int {
	return xxx_messageInfo_RequestComingReply.Size(m)
}
func (m *RequestComingReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestComingReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestComingReply proto.InternalMessageInfo

func (m *RequestComingReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type RequestGrpcServiceRequest struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGrpcServiceRequest) Reset()         { *m = RequestGrpcServiceRequest{} }
func (m *RequestGrpcServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RequestGrpcServiceRequest) ProtoMessage()    {}
func (*RequestGrpcServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{5}
}

func (m *RequestGrpcServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGrpcServiceRequest.Unmarshal(m, b)
}
func (m *RequestGrpcServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGrpcServiceRequest.Marshal(b, m, deterministic)
}
func (m *RequestGrpcServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGrpcServiceRequest.Merge(m, src)
}
func (m *RequestGrpcServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RequestGrpcServiceRequest.Size(m)
}
func (m *RequestGrpcServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGrpcServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGrpcServiceRequest proto.InternalMessageInfo

func (m *RequestGrpcServiceRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RequestGrpcServiceReply struct {
	GrpcHost             []byte   `protobuf:"bytes,1,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGrpcServiceReply) Reset()         { *m = RequestGrpcServiceReply{} }
func (m *RequestGrpcServiceReply) String() string { return proto.CompactTextString(m) }
func (*RequestGrpcServiceReply) ProtoMessage()    {}
func (*RequestGrpcServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{6}
}

func (m *RequestGrpcServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGrpcServiceReply.Unmarshal(m, b)
}
func (m *RequestGrpcServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGrpcServiceReply.Marshal(b, m, deterministic)
}
func (m *RequestGrpcServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGrpcServiceReply.Merge(m, src)
}
func (m *RequestGrpcServiceReply) XXX_Size() int {
	return xxx_messageInfo_RequestGrpcServiceReply.Size(m)
}
func (m *RequestGrpcServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGrpcServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGrpcServiceReply proto.InternalMessageInfo

func (m *RequestGrpcServiceReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

type RequestNsbServiceRequest struct {
	Name                 []byte   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestNsbServiceRequest) Reset()         { *m = RequestNsbServiceRequest{} }
func (m *RequestNsbServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RequestNsbServiceRequest) ProtoMessage()    {}
func (*RequestNsbServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{7}
}

func (m *RequestNsbServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestNsbServiceRequest.Unmarshal(m, b)
}
func (m *RequestNsbServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestNsbServiceRequest.Marshal(b, m, deterministic)
}
func (m *RequestNsbServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestNsbServiceRequest.Merge(m, src)
}
func (m *RequestNsbServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RequestNsbServiceRequest.Size(m)
}
func (m *RequestNsbServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestNsbServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RequestNsbServiceRequest proto.InternalMessageInfo

func (m *RequestNsbServiceRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RequestNsbServiceReply struct {
	NsbHost              []byte   `protobuf:"bytes,1,opt,name=nsb_host,json=nsbHost,proto3" json:"nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestNsbServiceReply) Reset()         { *m = RequestNsbServiceReply{} }
func (m *RequestNsbServiceReply) String() string { return proto.CompactTextString(m) }
func (*RequestNsbServiceReply) ProtoMessage()    {}
func (*RequestNsbServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{8}
}

func (m *RequestNsbServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestNsbServiceReply.Unmarshal(m, b)
}
func (m *RequestNsbServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestNsbServiceReply.Marshal(b, m, deterministic)
}
func (m *RequestNsbServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestNsbServiceReply.Merge(m, src)
}
func (m *RequestNsbServiceReply) XXX_Size() int {
	return xxx_messageInfo_RequestNsbServiceReply.Size(m)
}
func (m *RequestNsbServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestNsbServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_RequestNsbServiceReply proto.InternalMessageInfo

func (m *RequestNsbServiceReply) GetNsbHost() []byte {
	if m != nil {
		return m.NsbHost
	}
	return nil
}

type SessionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionListRequest) Reset()         { *m = SessionListRequest{} }
func (m *SessionListRequest) String() string { return proto.CompactTextString(m) }
func (*SessionListRequest) ProtoMessage()    {}
func (*SessionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{9}
}

func (m *SessionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListRequest.Unmarshal(m, b)
}
func (m *SessionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListRequest.Marshal(b, m, deterministic)
}
func (m *SessionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListRequest.Merge(m, src)
}
func (m *SessionListRequest) XXX_Size() int {
	return xxx_messageInfo_SessionListRequest.Size(m)
}
func (m *SessionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListRequest proto.InternalMessageInfo

type SessionListReply struct {
	SessionIds           [][]byte `protobuf:"bytes,1,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	GrpcHost             []byte   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	DefaultNsbHost       []byte   `protobuf:"bytes,3,opt,name=default_nsb_host,json=defaultNsbHost,proto3" json:"default_nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionListReply) Reset()         { *m = SessionListReply{} }
func (m *SessionListReply) String() string { return proto.CompactTextString(m) }
func (*SessionListReply) ProtoMessage()    {}
func (*SessionListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{10}
}

func (m *SessionListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionListReply.Unmarshal(m, b)
}
func (m *SessionListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionListReply.Marshal(b, m, deterministic)
}
func (m *SessionListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionListReply.Merge(m, src)
}
func (m *SessionListReply) XXX_Size() int {
	return xxx_messageInfo_SessionListReply.Size(m)
}
func (m *SessionListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionListReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionListReply proto.InternalMessageInfo

func (m *SessionListReply) GetSessionIds() [][]byte {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func (m *SessionListReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *SessionListReply) GetDefaultNsbHost() []byte {
	if m != nil {
		return m.DefaultNsbHost
	}
	return nil
}

type TransactionListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionListRequest) Reset()         { *m = TransactionListRequest{} }
func (m *TransactionListRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionListRequest) ProtoMessage()    {}
func (*TransactionListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{11}
}

func (m *TransactionListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListRequest.Unmarshal(m, b)
}
func (m *TransactionListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListRequest.Marshal(b, m, deterministic)
}
func (m *TransactionListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListRequest.Merge(m, src)
}
func (m *TransactionListRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionListRequest.Size(m)
}
func (m *TransactionListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListRequest proto.InternalMessageInfo

type TransactionListReply struct {
	// with help info
	Transactions         [][]byte `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	GrpcHost             []byte   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	DefaultNsbHost       []byte   `protobuf:"bytes,3,opt,name=default_nsb_host,json=defaultNsbHost,proto3" json:"default_nsb_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionListReply) Reset()         { *m = TransactionListReply{} }
func (m *TransactionListReply) String() string { return proto.CompactTextString(m) }
func (*TransactionListReply) ProtoMessage()    {}
func (*TransactionListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{12}
}

func (m *TransactionListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionListReply.Unmarshal(m, b)
}
func (m *TransactionListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionListReply.Marshal(b, m, deterministic)
}
func (m *TransactionListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionListReply.Merge(m, src)
}
func (m *TransactionListReply) XXX_Size() int {
	return xxx_messageInfo_TransactionListReply.Size(m)
}
func (m *TransactionListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionListReply.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionListReply proto.InternalMessageInfo

func (m *TransactionListReply) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *TransactionListReply) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *TransactionListReply) GetDefaultNsbHost() []byte {
	if m != nil {
		return m.DefaultNsbHost
	}
	return nil
}

type UserRegisterRequest struct {
	Account              *uiprpc_base.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserRegisterRequest) Reset()         { *m = UserRegisterRequest{} }
func (m *UserRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*UserRegisterRequest) ProtoMessage()    {}
func (*UserRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{13}
}

func (m *UserRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterRequest.Unmarshal(m, b)
}
func (m *UserRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterRequest.Marshal(b, m, deterministic)
}
func (m *UserRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterRequest.Merge(m, src)
}
func (m *UserRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_UserRegisterRequest.Size(m)
}
func (m *UserRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterRequest proto.InternalMessageInfo

func (m *UserRegisterRequest) GetAccount() *uiprpc_base.Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *UserRegisterRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type UserRegisterReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacteristicFlag   uint64   `protobuf:"varint,2,opt,name=characteristic_flag,json=characteristicFlag,proto3" json:"characteristic_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRegisterReply) Reset()         { *m = UserRegisterReply{} }
func (m *UserRegisterReply) String() string { return proto.CompactTextString(m) }
func (*UserRegisterReply) ProtoMessage()    {}
func (*UserRegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{14}
}

func (m *UserRegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRegisterReply.Unmarshal(m, b)
}
func (m *UserRegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRegisterReply.Marshal(b, m, deterministic)
}
func (m *UserRegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRegisterReply.Merge(m, src)
}
func (m *UserRegisterReply) XXX_Size() int {
	return xxx_messageInfo_UserRegisterReply.Size(m)
}
func (m *UserRegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_UserRegisterReply proto.InternalMessageInfo

func (m *UserRegisterReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UserRegisterReply) GetCharacteristicFlag() uint64 {
	if m != nil {
		return m.CharacteristicFlag
	}
	return 0
}

type SessionFinishedRequest struct {
	// isc_address
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IscState             uint32   `protobuf:"varint,2,opt,name=isc_state,json=iscState,proto3" json:"isc_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionFinishedRequest) Reset()         { *m = SessionFinishedRequest{} }
func (m *SessionFinishedRequest) String() string { return proto.CompactTextString(m) }
func (*SessionFinishedRequest) ProtoMessage()    {}
func (*SessionFinishedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{15}
}

func (m *SessionFinishedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionFinishedRequest.Unmarshal(m, b)
}
func (m *SessionFinishedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionFinishedRequest.Marshal(b, m, deterministic)
}
func (m *SessionFinishedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionFinishedRequest.Merge(m, src)
}
func (m *SessionFinishedRequest) XXX_Size() int {
	return xxx_messageInfo_SessionFinishedRequest.Size(m)
}
func (m *SessionFinishedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionFinishedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionFinishedRequest proto.InternalMessageInfo

func (m *SessionFinishedRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionFinishedRequest) GetIscState() uint32 {
	if m != nil {
		return m.IscState
	}
	return 0
}

type SessionFinishedReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionFinishedReply) Reset()         { *m = SessionFinishedReply{} }
func (m *SessionFinishedReply) String() string { return proto.CompactTextString(m) }
func (*SessionFinishedReply) ProtoMessage()    {}
func (*SessionFinishedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{16}
}

func (m *SessionFinishedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionFinishedReply.Unmarshal(m, b)
}
func (m *SessionFinishedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionFinishedReply.Marshal(b, m, deterministic)
}
func (m *SessionFinishedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionFinishedReply.Merge(m, src)
}
func (m *SessionFinishedReply) XXX_Size() int {
	return xxx_messageInfo_SessionFinishedReply.Size(m)
}
func (m *SessionFinishedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionFinishedReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionFinishedReply proto.InternalMessageInfo

func (m *SessionFinishedReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SessionRequestForInitRequest struct {
	// isc_address
	SessionId            []byte   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IscState             uint32   `protobuf:"varint,2,opt,name=isc_state,json=iscState,proto3" json:"isc_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequestForInitRequest) Reset()         { *m = SessionRequestForInitRequest{} }
func (m *SessionRequestForInitRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequestForInitRequest) ProtoMessage()    {}
func (*SessionRequestForInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{17}
}

func (m *SessionRequestForInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequestForInitRequest.Unmarshal(m, b)
}
func (m *SessionRequestForInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequestForInitRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequestForInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequestForInitRequest.Merge(m, src)
}
func (m *SessionRequestForInitRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequestForInitRequest.Size(m)
}
func (m *SessionRequestForInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequestForInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequestForInitRequest proto.InternalMessageInfo

func (m *SessionRequestForInitRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionRequestForInitRequest) GetIscState() uint32 {
	if m != nil {
		return m.IscState
	}
	return 0
}

type SessionRequestForInitReply struct {
	Opintents            [][]byte `protobuf:"bytes,1,rep,name=opintents,proto3" json:"opintents,omitempty"`
	Dependencies         [][]byte `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequestForInitReply) Reset()         { *m = SessionRequestForInitReply{} }
func (m *SessionRequestForInitReply) String() string { return proto.CompactTextString(m) }
func (*SessionRequestForInitReply) ProtoMessage()    {}
func (*SessionRequestForInitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{18}
}

func (m *SessionRequestForInitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequestForInitReply.Unmarshal(m, b)
}
func (m *SessionRequestForInitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequestForInitReply.Marshal(b, m, deterministic)
}
func (m *SessionRequestForInitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequestForInitReply.Merge(m, src)
}
func (m *SessionRequestForInitReply) XXX_Size() int {
	return xxx_messageInfo_SessionRequestForInitReply.Size(m)
}
func (m *SessionRequestForInitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequestForInitReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequestForInitReply proto.InternalMessageInfo

func (m *SessionRequestForInitReply) GetOpintents() [][]byte {
	if m != nil {
		return m.Opintents
	}
	return nil
}

func (m *SessionRequestForInitReply) GetDependencies() [][]byte {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type SessionRequireTransactRequest struct {
	// isc_address
	SessionId            []byte                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GrpcHost             []byte                   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	Tx                   *uiprpc_base.Transaction `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SessionRequireTransactRequest) Reset()         { *m = SessionRequireTransactRequest{} }
func (m *SessionRequireTransactRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequireTransactRequest) ProtoMessage()    {}
func (*SessionRequireTransactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{19}
}

func (m *SessionRequireTransactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequireTransactRequest.Unmarshal(m, b)
}
func (m *SessionRequireTransactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequireTransactRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequireTransactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequireTransactRequest.Merge(m, src)
}
func (m *SessionRequireTransactRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequireTransactRequest.Size(m)
}
func (m *SessionRequireTransactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequireTransactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequireTransactRequest proto.InternalMessageInfo

func (m *SessionRequireTransactRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *SessionRequireTransactRequest) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *SessionRequireTransactRequest) GetTx() *uiprpc_base.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type SessionRequireTransactReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequireTransactReply) Reset()         { *m = SessionRequireTransactReply{} }
func (m *SessionRequireTransactReply) String() string { return proto.CompactTextString(m) }
func (*SessionRequireTransactReply) ProtoMessage()    {}
func (*SessionRequireTransactReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{20}
}

func (m *SessionRequireTransactReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequireTransactReply.Unmarshal(m, b)
}
func (m *SessionRequireTransactReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequireTransactReply.Marshal(b, m, deterministic)
}
func (m *SessionRequireTransactReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequireTransactReply.Merge(m, src)
}
func (m *SessionRequireTransactReply) XXX_Size() int {
	return xxx_messageInfo_SessionRequireTransactReply.Size(m)
}
func (m *SessionRequireTransactReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequireTransactReply.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequireTransactReply proto.InternalMessageInfo

func (m *SessionRequireTransactReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AttestationReceiveRequest struct {
	// isc_address
	SessionId            []byte                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GrpcHost             []byte                   `protobuf:"bytes,2,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`
	Atte                 *uiprpc_base.Attestation `protobuf:"bytes,3,opt,name=atte,proto3" json:"atte,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AttestationReceiveRequest) Reset()         { *m = AttestationReceiveRequest{} }
func (m *AttestationReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*AttestationReceiveRequest) ProtoMessage()    {}
func (*AttestationReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{21}
}

func (m *AttestationReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationReceiveRequest.Unmarshal(m, b)
}
func (m *AttestationReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationReceiveRequest.Marshal(b, m, deterministic)
}
func (m *AttestationReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationReceiveRequest.Merge(m, src)
}
func (m *AttestationReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_AttestationReceiveRequest.Size(m)
}
func (m *AttestationReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationReceiveRequest proto.InternalMessageInfo

func (m *AttestationReceiveRequest) GetSessionId() []byte {
	if m != nil {
		return m.SessionId
	}
	return nil
}

func (m *AttestationReceiveRequest) GetGrpcHost() []byte {
	if m != nil {
		return m.GrpcHost
	}
	return nil
}

func (m *AttestationReceiveRequest) GetAtte() *uiprpc_base.Attestation {
	if m != nil {
		return m.Atte
	}
	return nil
}

type AttestationReceiveReply struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttestationReceiveReply) Reset()         { *m = AttestationReceiveReply{} }
func (m *AttestationReceiveReply) String() string { return proto.CompactTextString(m) }
func (*AttestationReceiveReply) ProtoMessage()    {}
func (*AttestationReceiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b2e2d651803ed170, []int{22}
}

func (m *AttestationReceiveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationReceiveReply.Unmarshal(m, b)
}
func (m *AttestationReceiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationReceiveReply.Marshal(b, m, deterministic)
}
func (m *AttestationReceiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationReceiveReply.Merge(m, src)
}
func (m *AttestationReceiveReply) XXX_Size() int {
	return xxx_messageInfo_AttestationReceiveReply.Size(m)
}
func (m *AttestationReceiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationReceiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationReceiveReply proto.InternalMessageInfo

func (m *AttestationReceiveReply) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Message)(nil), "wsrpc.Message")
	proto.RegisterType((*ClientHello)(nil), "wsrpc.ClientHello")
	proto.RegisterType((*ClientHelloReply)(nil), "wsrpc.ClientHelloReply")
	proto.RegisterType((*RequestComingRequest)(nil), "wsrpc.RequestComingRequest")
	proto.RegisterType((*RequestComingReply)(nil), "wsrpc.RequestComingReply")
	proto.RegisterType((*RequestGrpcServiceRequest)(nil), "wsrpc.RequestGrpcServiceRequest")
	proto.RegisterType((*RequestGrpcServiceReply)(nil), "wsrpc.RequestGrpcServiceReply")
	proto.RegisterType((*RequestNsbServiceRequest)(nil), "wsrpc.RequestNsbServiceRequest")
	proto.RegisterType((*RequestNsbServiceReply)(nil), "wsrpc.RequestNsbServiceReply")
	proto.RegisterType((*SessionListRequest)(nil), "wsrpc.SessionListRequest")
	proto.RegisterType((*SessionListReply)(nil), "wsrpc.SessionListReply")
	proto.RegisterType((*TransactionListRequest)(nil), "wsrpc.TransactionListRequest")
	proto.RegisterType((*TransactionListReply)(nil), "wsrpc.TransactionListReply")
	proto.RegisterType((*UserRegisterRequest)(nil), "wsrpc.UserRegisterRequest")
	proto.RegisterType((*UserRegisterReply)(nil), "wsrpc.UserRegisterReply")
	proto.RegisterType((*SessionFinishedRequest)(nil), "wsrpc.SessionFinishedRequest")
	proto.RegisterType((*SessionFinishedReply)(nil), "wsrpc.SessionFinishedReply")
	proto.RegisterType((*SessionRequestForInitRequest)(nil), "wsrpc.SessionRequestForInitRequest")
	proto.RegisterType((*SessionRequestForInitReply)(nil), "wsrpc.SessionRequestForInitReply")
	proto.RegisterType((*SessionRequireTransactRequest)(nil), "wsrpc.SessionRequireTransactRequest")
	proto.RegisterType((*SessionRequireTransactReply)(nil), "wsrpc.SessionRequireTransactReply")
	proto.RegisterType((*AttestationReceiveRequest)(nil), "wsrpc.AttestationReceiveRequest")
	proto.RegisterType((*AttestationReceiveReply)(nil), "wsrpc.AttestationReceiveReply")
}

func init() { proto.RegisterFile("wsrpc.proto", fileDescriptor_b2e2d651803ed170) }

var fileDescriptor_b2e2d651803ed170 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x4f, 0xdb, 0x30,
	0x14, 0xc7, 0x95, 0xd0, 0x8d, 0xf6, 0xb5, 0x43, 0x2c, 0x54, 0x50, 0x7e, 0x69, 0x2c, 0x9a, 0xa6,
	0x4e, 0x5b, 0x5b, 0x09, 0xa4, 0xdd, 0x19, 0x13, 0x83, 0x69, 0x70, 0x08, 0xec, 0xc2, 0x61, 0x95,
	0xeb, 0x3c, 0x52, 0x8b, 0xd4, 0xce, 0x6c, 0x97, 0xc1, 0x6e, 0x3b, 0xf0, 0x67, 0xec, 0x7f, 0x9d,
	0xec, 0xa4, 0x25, 0x81, 0xc0, 0x7a, 0xe0, 0xd4, 0xf8, 0xeb, 0xe7, 0xf7, 0x3e, 0x7e, 0xef, 0x9b,
	0x06, 0xea, 0xbf, 0x94, 0x4c, 0x68, 0x37, 0x91, 0x42, 0x0b, 0xef, 0x99, 0x5d, 0xac, 0xc1, 0x80,
	0x28, 0x4c, 0x25, 0xff, 0x10, 0xe6, 0x8f, 0x50, 0x29, 0x12, 0xa1, 0xb7, 0x06, 0x55, 0x2a, 0xb8,
	0x46, 0xae, 0x55, 0xcb, 0xd9, 0x72, 0xda, 0xb5, 0x60, 0xba, 0xf6, 0x3c, 0xa8, 0x9c, 0x4b, 0x31,
	0x6a, 0xb9, 0x5b, 0x4e, 0xbb, 0x11, 0xd8, 0x67, 0x6f, 0x01, 0x5c, 0x2d, 0x5a, 0x73, 0x56, 0x71,
	0xb5, 0xf0, 0x5f, 0x43, 0x7d, 0x2f, 0x66, 0xc8, 0xf5, 0x01, 0xc6, 0xb1, 0x30, 0x47, 0x38, 0x19,
	0xa1, 0x4d, 0xd5, 0x08, 0xec, 0xb3, 0xff, 0x15, 0x16, 0x73, 0x21, 0x01, 0x26, 0xf1, 0xb5, 0xb7,
	0x0e, 0xb5, 0x48, 0x26, 0xb4, 0x3f, 0x14, 0x4a, 0x67, 0xc1, 0x55, 0x23, 0x1c, 0x08, 0xa5, 0xbd,
	0x55, 0xa8, 0x72, 0x35, 0x48, 0xf7, 0xd2, 0xda, 0xf3, 0x5c, 0x0d, 0xcc, 0x96, 0xff, 0xd7, 0x81,
	0x66, 0x80, 0x3f, 0xc7, 0xa8, 0xf4, 0x9e, 0x18, 0x31, 0x1e, 0x65, 0x0b, 0x6f, 0x13, 0x40, 0xa1,
	0x52, 0x4c, 0xf0, 0x3e, 0x0b, 0xb3, 0x8c, 0xb5, 0x4c, 0x39, 0x0c, 0xbd, 0x2e, 0xcc, 0x13, 0x4a,
	0xc5, 0x98, 0xa7, 0x19, 0xeb, 0xdb, 0xcd, 0xee, 0x98, 0x25, 0xa6, 0x49, 0xb6, 0x2d, 0xbb, 0xe9,
	0x5e, 0x30, 0x09, 0x2a, 0xf2, 0xcd, 0x3d, 0xc2, 0x57, 0x29, 0xf2, 0xbd, 0x01, 0xef, 0x0e, 0x9e,
	0xb9, 0xed, 0x02, 0xb8, 0xe2, 0xc2, 0x42, 0x55, 0x03, 0x57, 0x5c, 0xf8, 0x3d, 0x58, 0xcd, 0xa2,
	0xbe, 0xc8, 0x84, 0x9e, 0xa0, 0xbc, 0x64, 0x14, 0x27, 0x37, 0x29, 0x6b, 0xe1, 0x47, 0x58, 0x29,
	0x3b, 0xf0, 0xbf, 0x4e, 0xfa, 0x5d, 0x68, 0x65, 0xe7, 0x8e, 0xd5, 0x60, 0x86, 0x3a, 0x3b, 0xb0,
	0x5c, 0x12, 0x6f, 0xca, 0xe4, 0xef, 0xec, 0x14, 0xef, 0xdc, 0x04, 0xef, 0x24, 0x6d, 0xf4, 0x37,
	0xa6, 0x74, 0x76, 0xde, 0xff, 0x0d, 0x8b, 0x05, 0xd5, 0x24, 0x79, 0x05, 0xf5, 0xdb, 0x21, 0x19,
	0xbf, 0xcd, 0xb5, 0x1b, 0x01, 0x4c, 0xa7, 0xa4, 0x8a, 0x97, 0x71, 0xef, 0xb4, 0xbd, 0x0d, 0x8b,
	0x21, 0x9e, 0x93, 0x71, 0xac, 0xfb, 0x53, 0x94, 0x74, 0x34, 0x0b, 0x99, 0x7e, 0x9c, 0x11, 0xb5,
	0x60, 0xf9, 0x54, 0x12, 0xae, 0x08, 0xd5, 0x77, 0xa8, 0xfe, 0x38, 0xd0, 0xbc, 0xb7, 0x65, 0xd0,
	0x7c, 0x68, 0xe8, 0x5b, 0x7d, 0xc2, 0x56, 0xd0, 0x9e, 0x8a, 0x6e, 0x00, 0x4b, 0xdf, 0x15, 0xca,
	0x00, 0x23, 0xa6, 0xb4, 0xf9, 0x4d, 0xe7, 0x91, 0xb3, 0xa8, 0x33, 0xa3, 0x45, 0xc7, 0x0a, 0x65,
	0xdf, 0x0e, 0xd1, 0x4d, 0x5f, 0x5d, 0x23, 0x1c, 0x9b, 0x41, 0x9e, 0xc2, 0xcb, 0x62, 0x8d, 0x12,
	0x1b, 0x7a, 0x3d, 0x58, 0xa2, 0x43, 0x22, 0x09, 0xd5, 0x28, 0x99, 0xd2, 0x8c, 0xf6, 0xcf, 0x63,
	0x12, 0xd9, 0x5c, 0x95, 0xc0, 0x2b, 0x6e, 0xed, 0xc7, 0x24, 0xf2, 0x4f, 0x61, 0x39, 0x9b, 0xe9,
	0x3e, 0xe3, 0x4c, 0x0d, 0x31, 0x9c, 0xf1, 0xf5, 0x5b, 0x87, 0x1a, 0x53, 0xb4, 0xaf, 0x34, 0xd1,
	0x29, 0xeb, 0x8b, 0xa0, 0xca, 0x14, 0x3d, 0x31, 0x6b, 0xff, 0x2d, 0x34, 0xef, 0x65, 0x2d, 0x7b,
	0x6b, 0xce, 0x60, 0x23, 0x8b, 0xcb, 0xaa, 0xee, 0x0b, 0x79, 0xc8, 0x99, 0x7e, 0x0a, 0x86, 0x1f,
	0xb0, 0xf6, 0x40, 0x6e, 0x43, 0xb2, 0x01, 0x35, 0x91, 0xb0, 0xe9, 0xbf, 0xa4, 0x71, 0xc6, 0xad,
	0x60, 0xac, 0x13, 0x62, 0x82, 0x3c, 0x44, 0x4e, 0x19, 0xaa, 0x96, 0x9b, 0x5a, 0x27, 0xaf, 0xf9,
	0x37, 0x0e, 0x6c, 0xe6, 0x0a, 0x30, 0x89, 0x13, 0x17, 0xce, 0x4e, 0xff, 0x98, 0xf7, 0x5c, 0x7d,
	0x65, 0xdd, 0x56, 0xdf, 0x6e, 0x15, 0x5c, 0x93, 0xf3, 0x7a, 0xe0, 0xea, 0x2b, 0xbf, 0x03, 0xeb,
	0x0f, 0x61, 0x94, 0xb5, 0xfc, 0xc6, 0x81, 0xd5, 0x5d, 0xad, 0xd1, 0x34, 0xcd, 0x9e, 0xa1, 0xc8,
	0x2e, 0xf1, 0x29, 0x90, 0x3f, 0x40, 0x85, 0x68, 0x8d, 0xa5, 0xd0, 0xf9, 0x8a, 0x36, 0xca, 0x7f,
	0x07, 0x2b, 0x65, 0x18, 0x25, 0xc8, 0x9f, 0x3a, 0x67, 0xef, 0x23, 0xa6, 0x87, 0xe3, 0x41, 0x97,
	0x8a, 0x51, 0xef, 0xe8, 0x5a, 0x32, 0x12, 0x76, 0x3e, 0x4b, 0x24, 0x23, 0xc6, 0x7b, 0x91, 0xe8,
	0x5c, 0xa2, 0xea, 0x19, 0x8a, 0x9e, 0xfd, 0x2c, 0x0e, 0x9e, 0xdb, 0x2f, 0xe2, 0xce, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc3, 0xfc, 0xf9, 0xc6, 0x33, 0x07, 0x00, 0x00,
}
