// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base.proto

package uiprpc_base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OpIntents struct {
	Contents             [][]byte `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	Dependencies         [][]byte `protobuf:"bytes,2,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpIntents) Reset()         { *m = OpIntents{} }
func (m *OpIntents) String() string { return proto.CompactTextString(m) }
func (*OpIntents) ProtoMessage()    {}
func (*OpIntents) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{0}
}

func (m *OpIntents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpIntents.Unmarshal(m, b)
}
func (m *OpIntents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpIntents.Marshal(b, m, deterministic)
}
func (m *OpIntents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpIntents.Merge(m, src)
}
func (m *OpIntents) XXX_Size() int {
	return xxx_messageInfo_OpIntents.Size(m)
}
func (m *OpIntents) XXX_DiscardUnknown() {
	xxx_messageInfo_OpIntents.DiscardUnknown(m)
}

var xxx_messageInfo_OpIntents proto.InternalMessageInfo

func (m *OpIntents) GetContents() [][]byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *OpIntents) GetDependencies() [][]byte {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type Transaction struct {
	ChainId              uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Src                  []byte   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Dst                  []byte   `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	Domain               []byte   `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Meta                 []byte   `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetSrc() []byte {
	if m != nil {
		return m.Src
	}
	return nil
}

func (m *Transaction) GetDst() []byte {
	if m != nil {
		return m.Dst
	}
	return nil
}

func (m *Transaction) GetDomain() []byte {
	if m != nil {
		return m.Domain
	}
	return nil
}

func (m *Transaction) GetMeta() []byte {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Signature struct {
	SignatureType        uint32   `protobuf:"varint,1,opt,name=signature_type,json=signatureType,proto3" json:"signature_type,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{2}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignatureType() uint32 {
	if m != nil {
		return m.SignatureType
	}
	return 0
}

func (m *Signature) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Account struct {
	ChainId              uint64   `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{3}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetChainId() uint64 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Account) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Attestation struct {
	Tid                  uint64       `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Aid                  uint64       `protobuf:"varint,2,opt,name=aid,proto3" json:"aid,omitempty"`
	Content              []byte       `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Signatures           []*Signature `protobuf:"bytes,4,rep,name=signatures,proto3" json:"signatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_db1b6b0986796150, []int{4}
}

func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attestation.Unmarshal(m, b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return xxx_messageInfo_Attestation.Size(m)
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetTid() uint64 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Attestation) GetAid() uint64 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *Attestation) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Attestation) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func init() {
	proto.RegisterType((*OpIntents)(nil), "uiprpc.base.OpIntents")
	proto.RegisterType((*Transaction)(nil), "uiprpc.base.Transaction")
	proto.RegisterType((*Signature)(nil), "uiprpc.base.Signature")
	proto.RegisterType((*Account)(nil), "uiprpc.base.Account")
	proto.RegisterType((*Attestation)(nil), "uiprpc.base.Attestation")
}

func init() { proto.RegisterFile("base.proto", fileDescriptor_db1b6b0986796150) }

var fileDescriptor_db1b6b0986796150 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xb1, 0x6b, 0xe3, 0x30,
	0x14, 0xc6, 0x71, 0xec, 0x8b, 0x93, 0xe7, 0xe4, 0x08, 0x1a, 0x82, 0xee, 0x26, 0x63, 0x38, 0xf0,
	0x12, 0x9b, 0xbb, 0xc0, 0x8d, 0x85, 0x94, 0x2e, 0xa1, 0x2d, 0x05, 0x37, 0x53, 0x97, 0xa0, 0x48,
	0xc2, 0xd1, 0x60, 0x49, 0x48, 0x72, 0x69, 0xe6, 0xfe, 0xe3, 0xc5, 0x8a, 0x63, 0x92, 0xa5, 0xdb,
	0xf7, 0xfd, 0xa4, 0xf7, 0xf4, 0x3d, 0x49, 0x00, 0x07, 0x62, 0x79, 0xa1, 0x8d, 0x72, 0x0a, 0x25,
	0xad, 0xd0, 0x46, 0xd3, 0xa2, 0x43, 0xd9, 0x23, 0x4c, 0x5f, 0xf4, 0x56, 0x3a, 0x2e, 0x9d, 0x45,
	0xbf, 0x61, 0x42, 0xd5, 0x59, 0xe3, 0x20, 0x0d, 0xf3, 0x59, 0x35, 0x78, 0x94, 0xc1, 0x8c, 0x71,
	0xcd, 0x25, 0xe3, 0x92, 0x0a, 0x6e, 0xf1, 0xc8, 0xaf, 0xdf, 0xb0, 0xec, 0x03, 0x92, 0x9d, 0x21,
	0xd2, 0x12, 0xea, 0x84, 0x92, 0xe8, 0x17, 0x4c, 0xe8, 0x91, 0x08, 0xb9, 0x17, 0x0c, 0x07, 0x69,
	0x90, 0x47, 0x55, 0xec, 0xfd, 0x96, 0xa1, 0x05, 0x84, 0xd6, 0x50, 0x3c, 0x4a, 0x83, 0x7c, 0x56,
	0x75, 0xb2, 0x23, 0xcc, 0x3a, 0x1c, 0x9e, 0x09, 0xb3, 0x0e, 0x2d, 0x61, 0xcc, 0x54, 0x43, 0x84,
	0xc4, 0x91, 0x87, 0xbd, 0x43, 0x08, 0xa2, 0x86, 0x3b, 0x82, 0x7f, 0x78, 0xea, 0x75, 0xf6, 0x04,
	0xd3, 0x57, 0x51, 0x4b, 0xe2, 0x5a, 0xc3, 0xd1, 0x1f, 0xf8, 0x69, 0x2f, 0x66, 0xef, 0x4e, 0x9a,
	0xfb, 0xd3, 0xe7, 0xd5, 0x7c, 0xa0, 0xbb, 0x93, 0xe6, 0x08, 0x43, 0xdc, 0x4f, 0xd7, 0xe7, 0xb8,
	0xd8, 0xec, 0x0e, 0xe2, 0x0d, 0xa5, 0xaa, 0x95, 0xee, 0xbb, 0x19, 0x30, 0xc4, 0x84, 0x31, 0xc3,
	0xad, 0xbd, 0xd4, 0xf7, 0x36, 0xfb, 0x0c, 0x20, 0xd9, 0x38, 0xc7, 0xad, 0x23, 0xfe, 0x22, 0x16,
	0x10, 0xba, 0xa1, 0xbe, 0x93, 0x1d, 0x21, 0x82, 0xf9, 0xba, 0xa8, 0xea, 0xe4, 0x75, 0x9a, 0xf0,
	0x26, 0x0d, 0xfa, 0x0f, 0x30, 0x04, 0xb7, 0x38, 0x4a, 0xc3, 0x3c, 0xf9, 0xb7, 0x2c, 0xae, 0x1e,
	0xb1, 0x18, 0x46, 0xaf, 0xae, 0x76, 0xde, 0xaf, 0xdf, 0xfe, 0xd6, 0xc2, 0x1d, 0xdb, 0x43, 0x41,
	0x55, 0x53, 0x3e, 0x9f, 0x8c, 0x20, 0x6c, 0xf5, 0x60, 0x38, 0x69, 0x84, 0x2c, 0x6b, 0xb5, 0x7a,
	0xe7, 0xb6, 0xac, 0x8d, 0xa6, 0xe5, 0xb9, 0xd5, 0xaa, 0x6b, 0x75, 0x18, 0xfb, 0x3f, 0xb2, 0xfe,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x9b, 0x5a, 0x76, 0x31, 0x02, 0x00, 0x00,
}
